### ISSUE TITLE
`bg-atlasapi` performs badly without an internet connection

### ISSUE THREAD

**Issue by adamltyson** [brainglobe/brainglobe-atlasapi#142]
`bg-atlasapi` should perform better without an internet connection. For example, we could cache the list of available atlases. If a user tries to use one that's not downloaded, then they can be warned that it's not possible without a network connection. 

The cache of atlas versions could be updated every time the GIN repo is queried.

**Comment by alessandrofelder** [comment]
This should address both when the user is not connected to the internet, and when GIN is down :grimacing: with good warnings/error messages.

**Comment by adamltyson** [comment]
@IgorTatarnikov following #358, do you think this can be closed, or is there more to do?

**Comment by IgorTatarnikov** [comment]
I think it can be closed!
