### ISSUE TITLE
Add new version of Waxholm rat atlas

### ISSUE THREAD

**Issue by adamltyson** [brainglobe/brainglobe-atlasapi#215]
https://www.nature.com/articles/s41592-023-02034-3

**Comment by adamltyson** [comment]
FYI @PolarBean

**Comment by PolarBean** [comment]
Ill be able to do this soon :)

**Comment by alessandrofelder** [comment]
I've uploaded the newest version of this to GIN, so 4.01 is now available via the atlas API.
