### ISSUE TITLE
issue installing editable version of bg-atlasgen

### ISSUE THREAD

**Issue by Robkozol** [brainglobe/brainglobe-atlasapi#226]
**Describe the bug**
I forked and cloned the repo to start integrating a cavefish atlas in the brain-globe project. However, I received a missing file error when I try to install an editable version of bg-atlasgen

**To Reproduce**
$ pip install e .
$ ERROR: File "setup.py" not found. Directory cannot be installed in editable mode: /Users/johannakowalko/bg-atlasgen (A "pyproject.toml" file was found, but editable mode currently requires a setup.py based build.)

Please let me know if there is a setup.py file that is missing for me to add to the bg-atlasgen directory, or whether I need to do an install using an alternative method.

Thank you,
Rob

**Comment by adamltyson** [comment]
I'm going to close this issue due to it's age. @Robkozol please feel free to get in touch if we can be of any help.

**Comment by Robkozol** [comment]
Hey Adam,

I was just getting back to this and looking to email you. I just started my
own lab and have had a very busy two months moving to NYC and getting
situated. During the fall I was able to get everything installed and
through loading packages via my python script. However, many of my lines of
code were working with no errors or tracebacks, but I wasn't generating any
files that should have been created and printed.

I was wondering if you could meet via zoom next week?

Thanks,
Rob

**Comment by alessandrofelder** [comment]
Superceded by #259
