### ISSUE TITLE
[Feature] Fix linter type comparison

### ISSUE THREAD

**Issue by alessandrofelder** [brainglobe/brainglobe-atlasapi#227]
**Is your feature request related to a problem? Please describe.**
Currently linting fails with
```bash
bg_atlasgen/atlas_scripts/admba_3d_dev_mouse.py:221:8: E721 Do not compare types, use `isinstance()`
bg_atlasgen/metadata_utils.py:51:12: E721 Do not compare types, use `isinstance()`
```

**Describe the solution you'd like**
Linting passes.

**Comment by adamltyson** [comment]
This was fixed (by the bot!) in https://github.com/brainglobe/bg-atlasgen/pull/66
