### ISSUE TITLE
[BUG] kim mouse atlas coordinate space

### ISSUE THREAD

**Issue by alessandrofelder** [brainglobe/brainglobe-atlasapi#229]
**Describe the bug**
kim_mouse_100um mesh and annotations are not in same coordinate system?

**To Reproduce**
Display the root mesh and the annotations image in `brainrender-napari` 

**Expected behaviour**
Root mesh and annotations images roughly overlap

**Log file**
n/a

**Screenshots**
![kim_mouse_100_bug](https://github.com/brainglobe/bg-atlasapi/assets/10500965/b5ee9787-9de3-45f6-875f-1401a9bbfc94)

**Computer used (please complete the following information):**

- OS: Ubuntu
- Version: 22.04.2 LTS

**Comment by adamltyson** [comment]
This is now fixed (I assume due to https://github.com/brainglobe/brainglobe-atlasapi/pull/271).
