### ISSUE TITLE
kim_mouse atlas plots only one hemisphere in brainrender

### ISSUE THREAD

**Issue by alowet** [brainglobe/brainglobe-atlasapi#236]
Using kim_mouse_50um, for which scaling issues have been solved (see brainglobe/brainglobe-atlasapi#247), individual brain regions plot in only one hemisphere or the other. Consider this snippet:

```
from brainrender import Scene

atlas = 'kim_mouse_50um'

# Create a brainrender scene
scene = Scene(screenshots_folder='.', inset=False, atlas_name=atlas)

# add actors
acbc = scene.add_brain_region('Acb', alpha=0.3, color='blue', hemisphere='both')

# render
scene.render(interactive=False, zoom=1)
scene.screenshot(name='example_{}'.format(atlas))
```
This produces the following output:
![example_kim_mouse_50um](https://user-images.githubusercontent.com/33499753/157293857-5507fae9-c9ca-4b1d-ad42-060080b025a7.png)

As you can see, the nucleus accumbens gets plotted only in the left hemisphere. This is contrary to the behavior of `allen_mouse_25um` and the documented behavior of the `hemisphere` parameter. As far as I can tell, this behavior does *not* affect the `structure_from_coords` function, i.e. that function correctly returns the same region regardless of whether the point is in the left or the right hemisphere. It's currently unclear to me whether this is a problem with the atlas API itself or with brainrender, but I figured I'd report the bug here because of the difference between `allen_mouse_25um` and `kim_mouse_50um`. If I should go to the brainrender Github instead, let me know.

**Comment by adamltyson** [comment]
This has now been fixed.
