### ISSUE TITLE
Automated minimal quality checks

### ISSUE THREAD

**Issue by FedeClaudi** [brainglobe/brainglobe-atlasapi#237]
Just putting this out here as a possible idea, but perhaps we can add some minimal test for working atlases?
These could include:

1. test on the atlas generation script, formatting, linting and trying to create the atlas (might be hard when it requires data that cannot be downloaded from a website)
2. test on atlas functionality: minimal tests for compatibility with the Atlas API, rendering in Brianrender etc...

Let me know your thoghts!

**Comment by adamltyson** [comment]
I think we can close this now we have the validation script. We can open new issues to either:
- Add more validators
- Change how we run them (e.g on CI)
