### ISSUE TITLE
Mesh generations: keeps only one hemisphere

### ISSUE THREAD

**Issue by FedeClaudi** [brainglobe/brainglobe-atlasapi#239]
The function `mesh_utils.extract_mesh_from_mask` call's vedo's `mesh.extractLargestRegion()` ([here](https://github.com/brainglobe/bg-atlasgen/blob/86caab99317359e5f791c991febb12589c5ced8a/bg_atlasgen/mesh_utils.py#L117)) after using marching cubes on a image stack to generate the mesh.

This is a problem for atlases with two hemispheres as brain regions which are not connected along the mid-line  will generate two large meshes and one will be excluded.  This has been fixed by others by selecting the two largest structures, but it remains to be implemented in the atlas generation code.

**Comment by adamltyson** [comment]
Going to close this as I assume it's been fixed, we haven't seen any issues generating atlases recently. We can reopen if needed.
