### ISSUE TITLE
[Feature] Add a template script

### ISSUE THREAD

**Issue by adamltyson** [brainglobe/brainglobe-atlasapi#242]
Currently, if someone wants to add a new atlas, they have to look though N atlas scripts and synthesise the key aspects themselves. We should provide a clear, well commented template script they can base their new script from.

(good idea thanks to @samclothier)

**Comment by alessandrofelder** [comment]
We have [at least an initial template script](https://github.com/brainglobe/brainglobe-atlasapi/blob/main/brainglobe_atlasapi/atlas_generation/atlas_scripts/template_script.py) - closing (but we will likely open new, related issues as we focus on atlas packaging in the next few months).
