### ISSUE TITLE
Mesh issue with the Princeton Mouse Brain Atlas

### ISSUE THREAD

**Issue by adamltyson** [brainglobe/brainglobe-atlasapi#251]
As [reported on image.sc](https://forum.image.sc/t/princeton-mouse-brain-atlas-offset-in-3d-space/92868) there seems to be an issue with the meshes of the Princeton Mouse Brain Atlas. They have some additional transform that means they don't align with e.g. the Allen atlas.

@viktorpm @alessandrofelder is this something that was caught in the validation scripts?

**Comment by alessandrofelder** [comment]
Hey, yes, this does indeed fail our validation test for the root mesh and the annotation have the same bounding box:
```
AssertionError: ('Mesh coordinate 618.5 and annotation coordinate 12360.0', 'differ by more than 10 times pixel size 20.0')
```
which is not surprising, seeing as opening the mesh and the annotations in napari looks like:
![image](https://github.com/brainglobe/brainglobe-atlasapi/assets/10500965/60b85f22-0110-4bce-a96d-83801348cf5f)

**Comment by alessandrofelder** [comment]
There's a dorso-ventral flip and a scale issue...

**Comment by alessandrofelder** [comment]
On the rotation/flip side here, a suspect is https://github.com/brainglobe/brainglobe-atlasapi/blob/e5296d7b6d62aa5151d650be3894e184128ebd3b/brainglobe_atlasapi/atlas_generation/atlas_scripts/princeton_mouse.py#L130

@viktorpm to test manually whether not rotating the annotation used to create meshes would help.

**Comment by dbirman** [comment]
Hey this seems to be closed but I haven't seen any update for the version in bgatlas, do I need to do something to see the new version? I get this currently:

```
╭───────────────────────────────── Brainglobe Atlases ─────────────────────────────────╮
│                                                                           Latest     │
│  Name                              Downloaded  Updated  Local version    version     │
│  princeton_mouse_20um                  ✔          ✔          1.0           1.0       │
```

Or was it updated without changing the version number and I just need to re-download?

**Comment by alessandrofelder** [comment]
Thanks for checking in @danbirman - we haven't managed to make time to upload the new version just yet - but aiming to do so on Monday! Thanks for your patience.

**Comment by dbirman** [comment]
Thanks @alessandrofelder, wanted to make sure I wasn't missing something on my end. Appreciate your time on this!

**Comment by alessandrofelder** [comment]
hey @dbirman 
this has been released now - thanks a lot to @viktorpm for his efforts on this! :tada: 

Make sure you have `brainglobe-atlasapi == 2.0.5` (e.g. by running `pip install --upgrade brainglobe-atlasapi` in your conda env) before attempting to update the atlas with the command line (we recently seem to have lost the entry point to do things like `brainglobe -update`, which is [now restored](https://github.com/brainglobe/brainglobe-atlasapi/pull/264)!).

Please shout if you run into problems, and thanks for your patience!

**Comment by dbirman** [comment]
Thank you @viktorpm and @alessandrofelder, there are a bunch of people who have been asking for this atlas. Really appreciate you spending time on this!
