### ISSUE TITLE
[BUG]Mesh issues with perens (20um) and kim (10um)

### ISSUE THREAD

**Issue by pderdeyn** [brainglobe/brainglobe-atlasapi#265]
**Describe the bug**
I'm using brainrender in napari to look at the perens (20um) and kim (10um) atlases and their meshes. When I load in meshes along with the reference layer, I find that the meshes do not appear inside of the reference layer

For perens, the mesh appears about the same size, but rotated and translated away from the reference
![image](https://github.com/brainglobe/brainglobe-atlasapi/assets/7269459/4a115ada-dd35-4956-accd-647c8291e823)

For kim, the mesh appears generally aligned but much smaller
![image](https://github.com/brainglobe/brainglobe-atlasapi/assets/7269459/8a2e478c-f774-40ff-95ad-3049a61b75f5)

**To Reproduce**
brainglobe-atlasapi 2.0.5
brainrender 2.1.6
brainrender-napari 0.0.3
kim mouse 10um v1.0 (10/26/2020)
perens lsfm mouse 20um v1.0 (5/31/2022)

**Expected behaviour**
I would expect the meshes to appear aligned in the reference layers, as they do for Allen mouse (10um and 25um) atlases that I have tested

**Computer used (please complete the following information):**

- OS: Windows 11

**Comment by pderdeyn** [comment]
At first I thought this behavior was related to this [similar issue](https://github.com/brainglobe/brainglobe-atlasapi/pull/253), but since each atlas has its own scripts for generating meshes these are likely separate issues. In fact, the perens and kim issues I report above may be separate issues themselves

**Comment by viktorpm** [comment]
Yes, we are working on it 🙂

**Comment by pderdeyn** [comment]
Thanks for the fix!
