### ISSUE TITLE
[BUG] the link to documentation in your github description is broken

### ISSUE THREAD

**Issue by PolarBean** [brainglobe/brainglobe-atlasapi#266]
**Describe the bug**
The link in your github description is broken

**To Reproduce**
it points to https://brainglobe.info/documentation/bg-atlasapi/index.html

**Expected behaviour**
it should point to https://brainglobe.info/documentation/brainglobe-atlasapi/index.html

**Comment by adamltyson** [comment]
Thanks @PolarBean, fixed!
