### ISSUE TITLE
[Feature] Add Ambystoma mexicanum (axolotl) atlas

### ISSUE THREAD

**Issue by adamltyson** [brainglobe/brainglobe-atlasapi#270]
Paper: https://doi.org/10.1038/s41598-021-89357-3
Data: https://zenodo.org/records/4595016

Looks very well organised, so shouldn't be too tricky to package up.

**Comment by alessandrofelder** [comment]
Atlas now available and [blog](https://github.com/brainglobe/brainglobe.github.io/pull/238) about to be published. Kudos to @saimaabdus19 and @dpshelio :clap: :tada:
