### ISSUE TITLE
perens_atlas alignment trouble with new version [BUG]

### ISSUE THREAD

**Issue by pr4deepr** [brainglobe/brainglobe-atlasapi#281]
Hi
   I have been registering my LSFM dataset to the perens atlas and it has been working well until the latest update to the atlas (1.1). 
When I checked the registration it was quite warped and looked out of proportion. 

Alignment results before update:
![image](https://github.com/brainglobe/brainglobe-atlasapi/assets/13831458/8e1b99f4-1ff0-4153-98f1-0e3ea872e02b)

After update:
![image](https://github.com/brainglobe/brainglobe-atlasapi/assets/13831458/e79a5f61-ecf8-4973-8a75-ae91e973f909)

I just used the `check orientation` option in the brainerender plugin and I get this:

![image](https://github.com/brainglobe/brainglobe-atlasapi/assets/13831458/6fb6d1dc-94b5-4202-ba28-bc258ccf37e7)

The orientation of my dataset is `sal` . 

Also, is it possible to roll back to the previous version of an atlas?

Cheers
Pradeep

**Comment by adamltyson** [comment]
Hi @pr4deepr, sorry about this, the new version seems to have been oriented incorrectly. We don't provide a way to easily roll back I'm afraid, but you can download any version of the atlas you need from [here](https://gin.g-node.org/BrainGlobe/atlases), untar it and place it in your `~/.brainglobe` directory (then make sure to not update, at least until we've fixed this). 

I will close this issue, but I've raised https://github.com/brainglobe/brainglobe-atlasapi/issues/282 to track.

**Comment by pr4deepr** [comment]
Thanks @adamltyson for the links to the atlases. 
Hope you're doing well..

**Comment by adamltyson** [comment]
I'm good thanks @pr4deepr, hope all is well in Melbourne!

The orientation of this atlas should be fixed now. When you get a minute, would you mind testing your pipeline with the latest version (1.2)?

**Comment by pr4deepr** [comment]
Thanks a lot. Its working now..
