### ISSUE TITLE
Enforce standardised orientation

### ISSUE THREAD

**Issue by adamltyson** [brainglobe/brainglobe-atlasapi#293]
A while ago we decided to not bother with `transform_to_bg`, but some atlases are still not in the standard `asr` orientation. Atlas should be regenerated in this orientation, and all functionality related to `transform_to_bg` removed.

Related to https://github.com/brainglobe/brainglobe-atlasapi/issues/213

**Comment by adamltyson** [comment]
@brainglobe/active-devs do we have any atlases that aren't `asr` now? If not, shall we document this orientation as a requirement and then close this issue?

**Comment by alessandrofelder** [comment]
>do we have any atlases that aren't asr now?

@viktorpm would probably know best?

**Comment by viktorpm** [comment]
All the ones on GIN should be in `asr`.

**Comment by alessandrofelder** [comment]
Fixed then 🎉
