### ISSUE TITLE
[Feature] Use pooch to handle atlas downloading

### ISSUE THREAD

**Issue by viktorpm** [brainglobe/brainglobe-atlasapi#323]
**Is your feature request related to a problem? Please describe.**

This is part of the effort to standardise atlas packaging scripts. 

**Describe the solution you'd like**

Replace inconsistent solutions to download and uncompress atlas files with pooch.

**Comment by adamltyson** [comment]
Closing as duplicate of https://github.com/brainglobe/brainglobe-atlasapi/issues/284
