### ISSUE TITLE
[Feature] add Perens MRI atlas

### ISSUE THREAD

**Issue by PolarBean** [brainglobe/brainglobe-atlasapi#337]
Alongside the Perens lsfm atlas there was also released a flat skull MRI atlas. its available at https://www.neuropedia.dk/resource/multimodal-3d-mouse-brain-atlas-framework-with-the-skull-derived-coordinate-system/

**Comment by adamltyson** [comment]
Thanks @PolarBean. I'm going to close this issue as it's already raised in #203

**Comment by PolarBean** [comment]
apologies I didn't see that!

**Comment by adamltyson** [comment]
No worries, it wasn't exactly detailed!
