### ISSUE TITLE
[BUG] mpin_zfish_1um hemispheres labels entire brain as one hemisphere

### ISSUE THREAD

**Issue by IgorTatarnikov** [brainglobe/brainglobe-atlasapi#360]
This is the current `hemispheres.tiff` overlayed on top of the `reference.tiff`. The entire image is marked as `1` apart from the very top row, where ~half is marked as `0`. 
![image](https://github.com/user-attachments/assets/7dfacf22-5938-47d0-9fe6-f530b2ed0da6)

This is present in the source data stored [here](https://gin.g-node.org/BrainGlobe/mpin_zfish).

This is the `mpin_zfish_hempispheres.tiff` file from the source data. Note the bottom row which matches the pattern of the packaged atlas `hemisphere.tiff` file.
![Screenshot from 2024-08-15 17-58-07](https://github.com/user-attachments/assets/de4ed486-da94-4382-ab4f-f39772178483)

**Comment by adamltyson** [comment]
Weird. No idea how we didn't notice this! Do we need a hemisphere file? The atlas does look non-symmetric.

**Comment by PolarBean** [comment]
https://github.com/brainglobe/brainglobe-atlasapi/issues/268

I think this is the same issue :)

**Comment by adamltyson** [comment]
Yes it is, thanks @PolarBean!

Closing in favour of #268
