### ISSUE TITLE
[Feature] DevCCFv1 atlas

### ISSUE THREAD

**Issue by carlocastoldi** [brainglobe/brainglobe-atlasapi#425]
related pubblication: https://www.nature.com/articles/s41467-024-53254-w
data: https://pennstateoffice365-my.sharepoint.com/:f:/g/personal/yuk17_psu_edu/EmCllFDonwtLvDD0xgWd7QYBuzVVvnSv4oKpUy7F9bx75Q?e=RxAmJa

website: https://kimlab.io/brain-map/DevCCF/

**Comment by adamltyson** [comment]
Thanks for raising this @carlocastoldi. I'm going to close this though as it's a duplocate of https://github.com/brainglobe/brainglobe-atlasapi/issues/225

**Comment by adamltyson** [comment]
If you need this atlas, and you'd like to contribute it to BrainGlobe, please let us know. We'd be happy to help.

**Comment by carlocastoldi** [comment]
Oh thank you!
I would love to contribute to BrainGlobe like i've done in the past. However it might not be something I can work on in the near future.

If i start working on it, I'll let you know!
