### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by dprotter** [brainglobe/brainglobe-atlasapi#434]
**Describe the bug**
Cannot launch brainrender due to HTTPS read timeout

Fresh install of brainglobe following the [install documentation ](https://brainglobe.info/documentation/index.html). Was able to launch napari. I successfully loaded the atlas manager plugin. There was a network connectivity error in the terminal, but it was able to begin downloading an atlas. However, Napari hung after it completed this download, and I was unable to do anything else. I force-quite napari. 

After restarting napari, I was unable to access any brainrender plugins without receiving an HTTPS timeout (However, I can successfully ping the address).

I removed the environment and re-installed, but have not be able to get the atlas manager to work since then. 

**To Reproduce**
Installed and ran brainglobe-napari

**Expected behaviour**

Open atlas manager
**Log file**
[brainrender_error.txt](https://github.com/user-attachments/files/17941137/brainrender_error.txt)

**Screenshots**
![image](https://github.com/user-attachments/assets/69ff1b6a-93cd-48ec-8dca-e56b8ccca901)

**Computer used (please complete the following information):**

- OS: MacOS (Intel)
- Version: 12.5.1
- Hardware specs: 32GB memory

**Additional context**

**Comment by adamltyson** [comment]
@dprotter I think this is still due to the hosting service. How we access it hasn't changed, but there have been many issues this week unfortunately.

**Comment by adamltyson** [comment]
I'm going to close this as the hosting service seems to be back online. Please feel free to raise any more issues if there are problems.
