### ISSUE TITLE
Hemisphere annotation correct?

### ISSUE THREAD

**Issue by horsto** [brainglobe/brainglobe-atlasapi#69]
Hi, I have a quick question about reading out hemisphere info as in `atlas.hemisphere_from_coords(coords,as_string=True)`. 
I have loaded a numpy array as `atlas = BrainGlobeAtlas("allen_mouse_50um")`
When reading out `coords` from left to right, I start from reading hemisphere as "left" and going into "right". So the red x here returns "left" as hemisphere and the blue x returns "right".
![Screenshot 2020-08-20 at 20 04 47](https://user-images.githubusercontent.com/7548928/90808513-6e776b00-e320-11ea-9b3a-354da811ac7f.png)
It should be the other way around (hemispheres are "mouse centered")? Or maybe I am doing something wrong?

**Comment by adamltyson** [comment]
Hi @horsto, maybe @vigji or @FedeClaudi can correct me, but I think the default orientation for the atlas images is rostral -> caudal, i.e. the first plane would be in olfactory bulb. Looking at the brain from the front like this looks correct.

**Comment by vigji** [comment]
Hei @horsto, I can confirm what @adamltyson is saying. The image looks correct to me as well!
